version: "3.7"
networks:
  capstone:  # Container들의 Private Network을 설정한다.
    ipam:
      config:
        - subnet: 172.20.1.0/24
volumes:  # Container 들에서 사용되는 Volume을 정의한다.
    capstone-redis: {}
# 띄울 컨테이너
services:
    capstone:
        container_name: capstone_be
        image: capstone_be
        build: # docker build 명령어를 사용할 때
            # docker build 명령어를 실행할 디렉토리 경로
            context: .
            dockerfile: Dockerfile        
        ports:
            - "8000:8000"          
        networks:
            capstone:
                ipv4_address: 172.20.1.4
        depends_on:                         
            - redis

    redis:
        container_name: capstone_redis
        image: redis:5.0.3-alpine
        ports:
            - "6379:6379"
        volumes:
            - capstone-redis:/data
        networks:
            capstone:
                ipv4_address: 172.20.1.3   

    celery:
        container_name: capstone_celery
        build:
            context: .
            dockerfile: Dockerfile
        command: celery -A backend worker -l info
        networks:
            capstone:
                ipv4_address: 172.20.1.5
        depends_on:                       
            - redis
            - capstone